/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background-100': 'var(--color-background-100)',
        'background-80': 'var(--color-background-80)',
        'background-60': 'var(--color-background-60)',
        'ink-100': 'var(--color-ink-100)',
        'ink-80': 'var(--color-ink-80)',
        'ink-60': 'var(--color-ink-60)',
        'ink-40': 'var(--color-ink-40)',
        'ink-20': 'var(--color-ink-20)',
        'ink-10': 'var(--color-ink-10)',
        'ink-05': 'var(--color-ink-05)',
        'black-opacity-100': 'var(--color-black-opacity-100)',
        'black-opacity-80': 'var(--color-black-opacity-80)',
        'black-opacity-60': 'var(--color-black-opacity-60)',
        'black-opacity-40': 'var(--color-black-opacity-40)',
        'black-opacity-20': 'var(--color-black-opacity-20)',
        'black-opacity-10': 'var(--color-black-opacity-10)',
        'black-opacity-05': 'var(--color-black-opacity-05)',
        'red-100': 'var(--color-red-100)',
        'red-80': 'var(--color-red-80)',
        'red-60': 'var(--color-red-60)',
        'red-40': 'var(--color-red-40)',
        'red-20': 'var(--color-red-20)',
        'red-10': 'var(--color-red-10)',
        'red-05': 'var(--color-red-05)',
        'red-circle': 'var(--color-red-circle)',
        'green-100': 'var(--color-green-100)',
        'green-80': 'var(--color-green-80)',
        'green-60': 'var(--color-green-60)',
        'green-40': 'var(--color-green-40)',
        'green-20': 'var(--color-green-20)',
        'green-10': 'var(--color-green-10)',
        'green-05': 'var(--color-green-05)',
        'green-circle': 'var(--color-green-circle)',
        'yellow-100': 'var(--color-yellow-100)',
        'yellow-80': 'var(--color-yellow-80)',
        'yellow-60': 'var(--color-yellow-60)',
        'yellow-40': 'var(--color-yellow-40)',
        'yellow-20': 'var(--color-yellow-20)',
        'yellow-10': 'var(--color-yellow-10)',
        'yellow-05': 'var(--color-yellow-05)',
        'orange-100': 'var(--color-orange-100)',
        'orange-80': 'var(--color-orange-80)',
        'orange-60': 'var(--color-orange-60)',
        'orange-40': 'var(--color-orange-40)',
        'orange-20': 'var(--color-orange-20)',
        'orange-10': 'var(--color-orange-10)',
        'orange-05': 'var(--color-orange-05)',
        'blue-100': 'var(--color-blue-100)',
        'blue-80': 'var(--color-blue-80)',
        'blue-60': 'var(--color-blue-60)',
        'blue-40': 'var(--color-blue-40)',
        'blue-20': 'var(--color-blue-20)',
        'blue-10': 'var(--color-blue-10)',
        'blue-05': 'var(--color-blue-05)',
        'teal-100': 'var(--color-teal-100)',
        'teal-80': 'var(--color-teal-80)',
        'teal-60': 'var(--color-teal-60)',
        'teal-40': 'var(--color-teal-40)',
        'teal-20': 'var(--color-teal-20)',
        'teal-10': 'var(--color-teal-10)',
        'teal-05': 'var(--color-teal-05)',
        'indigo-100': 'var(--color-indigo-100)',
        'indigo-80': 'var(--color-indigo-80)',
        'indigo-60': 'var(--color-indigo-60)',
        'indigo-40': 'var(--color-indigo-40)',
        'indigo-20': 'var(--color-indigo-20)',
        'indigo-10': 'var(--color-indigo-10)',
        'indigo-05': 'var(--color-indigo-05)',
        'purple-100': 'var(--color-purple-100)',
        'purple-80': 'var(--color-purple-80)',
        'purple-60': 'var(--color-purple-60)',
        'purple-40': 'var(--color-purple-40)',
        'purple-20': 'var(--color-purple-20)',
        'purple-10': 'var(--color-purple-10)',
        'purple-05': 'var(--color-purple-05)',
        dropdown: '#282624',
      },
      backgroundImage: {
        'star-100': 'var(--color-star-100)',
        'primary-100': 'var(--color-primary-100)',
        'primary-80': 'var(--color-primary-80)',
        'primary-60': 'var(--color-primary-60)',
        'primary-40': 'var(--color-primary-40)',
        'primary-20': 'var(--color-primary-20)',
        'primary-10': 'var(--color-primary-10)',
        'primary-05': 'var(--color-primary-05)',
        'login-background': "url('../assets/images/Login_out_Background.png')",
        'login-mobile-background':
          "url('../assets/images/Login_out_Mobile_Background.png')",
      },
      opacity: {
        2: '0.02',
      },
      spacing: {
        13: '3.25rem',
        15: '3.75rem',
      },
      lineHeight: {
        11: '2.75rem',
      },
      screens: {
        '3xl': '1800px',
      },
    },
    fontSize: {
      xs: ['0.75rem', '1.25rem'],
      sm: ['0.875rem', '1.375rem'],
      base: ['1rem', '1.5rem'],
      lg: ['1.25rem', '1.75rem'],
      xl: ['1.25rem', '1.75rem'],
      '2xl': ['1.5rem', '2rem'],
      '3xl': ['1.875rem', '2.25rem'],
      '3.5xl': ['2rem', '2.5rem'],
      '4xl': ['2.25rem', '2.75rem'],
      '5xl': ['3rem', '3.5rem'],
      '6xl': ['3.75rem', '4.25rem'],
    },
  },
  plugins: [],
  darkMode: 'class',
};
