// Generated by https://quicktype.io

export default interface AutoBotManagementList {
    count: number | null;
    next: number | string | null;
    previous: number | string | null;
    results: AutoBotManagementListResult[];
}

export interface AutoBotManagementListResult {
    id: number;
    name: string;
    description: string;
}
