// Generated by https://quicktype.io

export default interface AutoBotSetting {
    count: number | null;
    next: number | null;
    previous: number | null;
    results: AutoBotSettingResult[];
}

export interface AutoBotSettingResult {
    // Custom FIELD
    checkbox?: string;
    profitAndTotalProfit?: string;
    profit_per_day?: string;
    actions?: string;
    select_account_type?: string;
    select_partner_account?: string;
    profitLoss?: string;
    [x: string]: any

    young_loss: any

    // FIELDs From API
    id: number;
    config_name: string;
    follower: number;
    follower_name: string;
    follower_username: string;
    account_type: string;
    young_profit: any;
    second_action: number;
    budgetmanagement_id: number;
    budgetmanagement_name: string;
    increase_type: number;
    step_type: number;
    o_amount: number;
    order_value: OrderValue;
    orderValueText: string;
    aim_min: number;
    aim_max: number;
    current_profit: number;
    current_date_profit: number;
    current_volume: number;
    current_date_volume: number;
    total_win: number;
    total_lose: number;
    status: string;
    block_status: string;
    o_owner: number;
    auto_fillindemo: boolean;
    signal_id: number | null;
    singal_name: string;
    signalpersonal_id: number | null,
    signalpersonal_name: string,
    reverse: boolean;
    condition_fire: boolean;
    fire_one: number;
    fire_two: number;
    fire_three: number;
    fire_four: number;
    created_at: string;
    updated_at: string;
    date: string;
    is_master: boolean;
}

// Generated by https://quicktype.io

type OrderValue = {
    [key: string]: (number | string)[];
};
