// Generated by https://quicktype.io

export default interface AutoBotSettingUpdate {
    config_name?: string;
    follower?: number;
    follower_name?: string | null;
    budgetmanagement_id?: number;
    budgetmanagement_name?: string | null;
    signal_id?: number;
    signalpersonal_id?: number;
    singal_name?: string | null;
    current_profit?: number;
    current_date_profit?: number;
    young_loss?: any;
    current_volume?: number;
    current_date_volume?: number;
    reverse?: boolean;
    account_type?: string;
    young_profit?: any;
    second_action?: number;
    o_amount?: number;
    order_value?: OrderValueRequest | string | OrderValue;
    aim_min?: number;
    isSignal?: boolean,
    aim_max?: number;
    increase_type?: number;
    step_type?: number;
    status?: string;
    block_status?: string;
    auto_fillindemo?: boolean;
    condition_fire?: boolean;
    fire_one?: number;
    fire_two?: number;
    fire_three?: number;
    fire_four?: number;
    buget_position?: {};
    is_master?: boolean;
}

export interface OrderValueRequest {
    additionalProp1: string;
    additionalProp2: string;
    additionalProp3: string;
}

type OrderValue = {
    [key: string]: (number | string)[];
};