// Generated by https://quicktype.io

export interface AutoBotHistoryTelegramList {
    count: number | null;
    next: string | null;
    previous: string | null;
    results: AutoBotHistoryTelegramListResult[];
}

export interface AutoBotHistoryTelegramListResult {
    // CUSTOM
    checkbox?: string;
    young_profit?: number;
    current_profit?: number;
    config_name?: number;
    output?: number;

    // CUSTOM
    id: number | string;
    o_id: number;
    ss_id: number;
    o_amount: number;
    o_fold: number;
    o_type: string;
    account_type: string;
    o_time: number;
    o_owner: number;
    o_PartnerAcc_owner: number;
    o_PartnerAcc_owner_name: string;
    master: number;
    master_name: string;
    follow_configid: number;
    o_status: string;
    o_result: number;
    created_at: string;
    updated_at: string;
    date: string;
    trade_type: string;
}