// Generated by https://quicktype.io

export interface BotCopyTrade {
    account_type?: string | number;
    master: string | number;
    master_name?: string | number;
    follower: number;
    follower_name?: string;
    o_amount: number;
    fold_command: number;
    aim_min: number;
    aim_max: number;
    ai_bot_telegram_enabled?: boolean;
    ai_basic_enabled?: boolean;
    copy_trade_enabled?: boolean;
    status?: string;
}
