// Generated by https://quicktype.io

export interface BotPlaceOrderResponse {
    ok: boolean;
    d:  D;
}

export interface D {
    o_id:     number;
    ss_id:    number;
    o_time:   number;
    o_amount: number;
    o_type:   string;
}
