// Generated by https://quicktype.io

export default interface BotSignalPersonal {
    count: number | null;
    next: string | null;
    previous: string | null;
    results: BotSignalPersonalResult[];
}

type BubbleOptions = {
    [key: string]: any;
  };
  

interface TypeConditionChid {
    board: number //Bảng
    bubble: number //Bóng
    result_type: number // 1/2
    id: string
  }
  
  interface TypeConditionsForm {
    betType: number
    bubble: number
    conditions: TypeConditionChid[]
    fconditions: BubbleOptions
    id: string
  }

export interface BotSignalPersonalResult {
    // Custom
    checkbox?: string;
    actions?: string;

    id: number;
    config_name: string;
    owner_type: string;
    config_type: string;
    conditions: Conditions;
    fconditions: TypeConditionsForm[];
    is_onlytrade?: boolean;
}

export interface Conditions {
    [key: string]: {
        [key: string]: any;
    }
}

