// Generated by https://quicktype.io

export default interface CopyTradeOrderHistory {
    // FIELDS FROM API
    count: number | null;
    next: number | null;
    previous: number | null;
    results: CopyTradeOrderHistoryResult[];
}


export interface CopyTradeOrderHistoryResult {
    // CUSTOM FIELDS
    checkbox?: string;
    output?: number;

    // FIELDS FROM API
    // id: string | number;
    // o_id: number;
    // ss_id: number;
    // o_amount: number;
    // o_fold: number;
    // o_type: string;
    // o_time: number;
    // o_owner: number;
    // o_PartnerAcc_owner: number;
    // o_PartnerAcc_owner_name: string;
    // o_status: string;
    // o_result: number;
    // created_at: string;
    // updated_at: string;
    // trade_type: string;

    id:                      string | number;
    o_id:                    number;
    ss_id:                   number;
    o_amount:                number;
    o_fold:                  number;
    o_type:                  string;
    account_type:            string;
    o_time:                  number;
    o_owner:                 number;
    o_PartnerAcc_owner:      number;
    o_PartnerAcc_owner_name: string;
    master:                  number;
    master_name:             string;
    follow_configid:         number;
    o_status:                string;
    o_result:                number;
    created_at:              string;
    updated_at:              string;
    date:                    string;
    trade_type:              string;
}
// Generated by https://quicktype.io

export interface TopLevel {
    id:                      number;
    o_id:                    number;
    ss_id:                   number;
    o_amount:                number;
    o_fold:                  number;
    o_type:                  string;
    account_type:            string;
    o_time:                  number;
    o_owner:                 number;
    o_PartnerAcc_owner:      number;
    o_PartnerAcc_owner_name: string;
    master:                  number;
    master_name:             string;
    follow_configid:         number;
    o_status:                string;
    o_result:                number;
    created_at:              string;
    updated_at:              string;
    date:                    string;
    trade_type:              string;
}

