// Generated by https://quicktype.io

export default interface CopyTradeSelfOrderHistory {
    count: number | null;
    next: number | null;
    previous: number | null;
    results: CopyTradeSelfOrderHistoryResult[];
}

export interface CopyTradeSelfOrderHistoryResult {
    //CUSTOM
    checkbox?: string;
    output?: number;

    //API
    id: number;
    o_id: number;
    ss_id: number;
    o_amount: number;
    o_fold: number;
    o_type: string;
    account_type: string;
    o_time: number;
    o_owner: number;
    o_PartnerAcc_owner: number;
    o_PartnerAcc_owner_name: string;
    master: number;
    follow_configid: null;
    o_status: string;
    o_result: number;
    created_at: string;
    updated_at: string;
    date: string;
    trade_type: string;
}

