// Generated by https://quicktype.io

export default interface UserHistoryResponse {
  count: number | null;
  next: string | null;
  previous: string | null;
  results: UserHistoryResponseResult[];
}

export interface UserHistoryResponseResult {
  // Custom
  checkbox?: string;
  actions?: string;

  id: number | string;
  date: Date;
  ip: string;
}
