// Generated by https://quicktype.io

export default interface UserManagementUserResponse {
  count: number | null;
  next: string | null;
  previous: string | null;
  results: UserManagementUserResponseResult[];
}

export interface UserManagementUserResponseResult {
  // Custom
  checkbox?: string;
  actions?: string;

  id: number | string;
  follower_name: string;
  email: string;
  status: string;
}
