// Generated by https://quicktype.io

export default interface AutoBotSettingRequest {
    config_name: string;
    follower: number;
    account_type: string;
    reverse: boolean;
    young_profit?: any;
    second_action: number;
    isSignal?: boolean;
    budgetmanagement_id: number;
    o_amount: number;
    order_value?: OrderValueRequest | null | string | OrderValue;
    aim_min: number;
    aim_max: number;
    young_loss?: any;
    increase_type: number;
    step_type: number;
    status: string;
    block_status: string;
    auto_fillindemo: boolean;
    signal_id?: number;
    signalpersonal_id?: number;
    condition_fire: boolean;
    fire_one: number;
    fire_two: number;
    fire_three: number;
    fire_four: number;
    buget_position: {};
    is_master: boolean;
}

export interface OrderValueRequest {
    additionalProp1: string;
    additionalProp2: string;
    additionalProp3: string;
}

type OrderValue = {
    [key: string]: (number | string)[];
};
