// Generated by https://quicktype.io

export default interface DashboardResetRequest {
    owner?:          number;
    current_profit?: number;
    volume?:         number;
    total_win?:      number;
    total_lose?:     number;
    account_type?:   string;
    total_draft?:    number;
}
